name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write   # required for OIDC

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.7"
      - run: python -m pip install --upgrade build
      - run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write   # required for OIDC
- uses: pypa/gh-action-pypi-publish@release/v1
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.7"
      - run: python -m pip install --upgrade build
      - run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
